# Generated by Django 5.1.6 on 2025-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbotlive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='channel_id',
            field=models.CharField(default='fs', max_length=255),
        ),
    ]
