# Generated by Django 5.1.6 on 2025-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbotlive', '0002_cs_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='channel_id',
            field=models.CharField(max_length=255),
        ),
    ]
